### ISSUE TITLE
Invalid site key

### ISSUE THREAD

**Issue by mediageni** [Emiller88/MoneroFaucet#2]
Hi, where can I set the site key?

It is saying "Coinhive Error: invalid_site_key"

**Comment by edmundmiller** [comment]
@scriptgeni Sorry for missing this. Please check with [coinhive-stratum-mining-proxy](https://github.com/x25/coinhive-stratum-mining-proxy)

**Comment by edmundmiller** [comment]
Or you can edit it in  [MoneroFaucet/assets/js/startXMRminer.js ](https://github.com/Emiller88/MoneroFaucet/blob/master/assets/js/startXMRminer.js)
